## Difficulty Level Beginner

 1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [12]:
x = np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [13]:
np.shape(x)

(39,)

5. Print the type of the previous array in question 3

In [14]:
type(x)

numpy.ndarray

6. Print the numpy version and the configuration

In [15]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
None


7. Print the dimension of the array in question 3

In [17]:
x.ndim

1

8. Create a boolean array with all the True values

In [20]:
arr1 = np.array([[0., 2., 4.], [1., 3., 5.]])
arr1



array([[0., 2., 4.],
       [1., 3., 5.]])

In [19]:
arr2 = np.array([[2., 4., 6.], [3., 5., 7.]])
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [21]:
arr2 > arr1

array([[ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array

In [22]:
np.array([[2, 4, 6], [6, 8, 10]])

array([[ 2,  4,  6],
       [ 6,  8, 10]])

10. Create a three dimensional array

In [29]:
np.array([[[2, 4, 6], [6, 8, 10], [8, 10, 12]]])

array([[[ 2,  4,  6],
        [ 6,  8, 10],
        [ 8, 10, 12]]])

## Difficulty Level Easy

1. Reverse a vector (first element becomes last)

In [30]:
y = np.arange(12, 38)
y

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [35]:
y = y[::-1]
y

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

2. Create a null vector of size 10 but the fifth value which is 1

In [37]:
z = np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

3. Create a 3x3 identity matrix

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. arr = np.array([1, 2, 3, 4, 5])
    #### Convert the data type of the given array from int to float

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [42]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

5. (a) arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

   (b) arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
           
#### Multiply arr1 with arr2

In [46]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

6. (a) arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

   (b)arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
#### Make an array by comparing both the arrays provided above

In [49]:
arr1 = np.array([[1., 2., 3.],

     [4., 5., 6.]]) 
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr2 = np.array([[0., 4., 1.],

     [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [55]:
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

7. Extract all odd numbers from arr with values(0-9)

In [201]:
odd = np.array([1,2,3,4,5,6,7,8,9])
odd[odd % 2 == 1]

array([1, 3, 5, 7, 9])

8. Replace all odd numbers to -1 from previous array

In [112]:
odd = np.array([1,2,3,4,5,6,7,8,9])
np.where( odd%2 == 1, -1, odd )

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

9. arr = np.arange(10)
#### Replace the values of indexes 5,6,7 and 8 to 12

In [128]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

10. Create a 2d array with 1 on the border and 0 inside

In [141]:
x = np.ones((6,6))
x [1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Difficulty Level Medium

1. arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
#### Replace the value 5 to 12

In [165]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
arr2d [arr2d == 5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [186]:
arr2d [1]

array([ 4, 12,  6])

2. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#### Convert all the values of 1st array to 64

In [188]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [264]:
arrS= arr3d[0] #Method:1
arrS [:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [266]:
old_values = arr3d[0].copy() #Method:2
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

3. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [268]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [269]:
array1[1:]

array([[3, 4, 5],
       [6, 7, 8]])

4. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [270]:
array2 = np.arange(9).reshape(3,3)
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [293]:
array2[1, :2]

array([3, 4])

5. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [49]:
#array2 = np.array([[0,1,2,3,4,5,6,7,8,9]])
#array2

ValueError: cannot reshape array of size 10 into shape (3,3)

In [294]:
#array2 = np.arange(9).reshape(3,3)
#array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
#array2.ndim

2

In [48]:
#array2[0:, 0:-1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

6. Create a 10x10 array with random values and find the minimum and maximum values

In [300]:
ran = np.random.random((10,10))
ran

array([[0.85383317, 0.68460771, 0.5908744 , 0.83825312, 0.21226341,
        0.79899551, 0.99756962, 0.48701544, 0.49214036, 0.46693219],
       [0.50300065, 0.96246391, 0.50729828, 0.72016524, 0.51734283,
        0.67398523, 0.45202464, 0.54917625, 0.16252037, 0.28669988],
       [0.90319382, 0.84255048, 0.75429355, 0.03193889, 0.95113501,
        0.0896452 , 0.85755   , 0.49726782, 0.26427333, 0.87514546],
       [0.57605906, 0.66258854, 0.00117454, 0.0460897 , 0.94545497,
        0.54302354, 0.21849434, 0.2375403 , 0.0573708 , 0.9305872 ],
       [0.76059466, 0.77926845, 0.54255399, 0.81552206, 0.76839273,
        0.6785042 , 0.42040577, 0.29842039, 0.72897155, 0.50434278],
       [0.74328638, 0.191973  , 0.68107785, 0.25241932, 0.76688906,
        0.10645565, 0.07694838, 0.89988847, 0.08588499, 0.9484777 ],
       [0.67962903, 0.36051724, 0.18565482, 0.94007349, 0.52118295,
        0.0999531 , 0.70145459, 0.92934707, 0.56049974, 0.31341675],
       [0.41526142, 0.78086419, 0.7438909

In [301]:
ran.min()

0.001174543446178622

In [302]:
ran.max()

0.9975696182335387

7. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#### Find the common items between a and b

In [307]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [305]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [306]:
np.intersect1d (a, b)

array([2, 4])

8. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#### Find the positions where elements of a and b match

In [312]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [313]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [314]:
np.where(a==b)

(array([1, 3, 5, 7]),)

9. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#### Find all the values from array data where the values from array names are not equal to Will

In [333]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

In [336]:
data = np.random.randn(7, 4)
data

array([[ 1.48758905e+00, -1.48030658e+00,  4.67037653e-01,
         4.87916439e-01],
       [-8.20079651e-01, -3.34564071e+00,  1.37434838e+00,
        -4.05842702e-01],
       [ 5.95662580e-01, -1.65680659e+00,  2.74786692e-03,
         5.22602540e-01],
       [ 2.94823442e-01, -1.29335334e+00,  8.36373139e-02,
        -9.18569562e-01],
       [ 5.98596972e-01,  2.02422277e-01, -1.06460716e+00,
         2.13150174e+00],
       [-4.05901849e-01, -8.38258263e-01,  9.24780330e-01,
        -5.14135735e-02],
       [ 3.37707067e-01, -2.12968205e+00,  2.10894908e+00,
        -1.57342050e+00]])

In [337]:
data[names != 'Will']

array([[ 1.48758905, -1.48030658,  0.46703765,  0.48791644],
       [-0.82007965, -3.34564071,  1.37434838, -0.4058427 ],
       [ 0.29482344, -1.29335334,  0.08363731, -0.91856956],
       [-0.40590185, -0.83825826,  0.92478033, -0.05141357],
       [ 0.33770707, -2.12968205,  2.10894908, -1.5734205 ]])

10.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#### Find all the values from array data where the values from array names are not equal to Will and Joe

In [349]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
mask = (names != 'Joe') & (names != 'Will')
mask

array([ True, False, False,  True, False, False, False])

In [350]:
data = np.random.randn(7, 4)
data[mask]

array([[-1.66928377,  3.94169071, -0.68009821,  1.1751553 ],
       [-2.38360691,  0.79040302,  1.48599289, -1.48750979]])

## Difficulty Level Hard

1. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [385]:
array1 = np.arange(1,16).reshape(5,3)
array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [386]:
array1 = array1.astype('float64') 
array1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [387]:
array1.dtype

dtype('float64')

2. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [383]:
array2 = np.arange(1,17).reshape(2, 2, 4)
array2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [382]:
array2 = array2.astype('float64') 
array2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [384]:
array2.dtype

dtype('int64')

3. Swap axes of the array you created in Question 32

In [4]:
import numpy as np
arr = np.arange(1,17).reshape(2, 2, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [20]:
np.swapaxes(arr,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

4. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [50]:
#arr = np.array([2,0.43,0.85,23,34,87,0.50,4,16,25,8])
#arr

array([ 2.  ,  0.43,  0.85, 23.  , 34.  , 87.  ,  0.5 ,  4.  , 16.  ,
       25.  ,  8.  ])

In [51]:
#a = np.sqrt(arr)
#a

array([1.41421356, 0.65574385, 0.92195445, 4.79583152, 5.83095189,
       9.32737905, 0.70710678, 2.        , 4.        , 5.        ,
       2.82842712])

In [53]:
#a [a < 0.5] = 0.0
#a

array([1.41421356, 0.65574385, 0.92195445, 4.79583152, 5.83095189,
       9.32737905, 0.70710678, 2.        , 4.        , 5.        ,
       2.82842712])

5. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays